on:
  push:
    branches:
      - master
  pull_request:

name: Tests

jobs:

  test:
    name: Tests
    strategy:
        matrix:
          node: [18, 20, 22]
          os: [windows-latest, ubuntu-20.04, ubuntu-22.04, ubuntu-24.04, macOS-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}

      - run: yarn

      - run: yarn test
