on:
  push:
    branches:
      - master
  pull_request:

name: Tests

jobs:

  test:
    name: Tests
    strategy:
        matrix:
          node: [18, 20, 22]
          os: [windows-2016, ubuntu-16.04, ubuntu-18.04, macOS-latest]
          arch: [x86, x64]
          exclude:
            - os: ubuntu-16.04
              arch: x86
            - os: ubuntu-18.04
              arch: x86
            - os: macOS-latest
              arch: x86
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          architecture: ${{ matrix.arch }}

      - run: yarn

      - run: yarn test
